## Config file for automatic testing at travis-ci.org
#version: ~> 1.0
#
#language: python
#os: linux
#dist: focal
#
#python:
#  - "3.7"
#  - "3.8"
#  - "3.9"
#  - "3.10"
#  - "pypy3"
#
#install:
#    - pip install .
#    - pip install -r requirements-dev.txt
#    - rm -rf build/
#
#jobs:
#  include:
#    - language: python
#    - python: "pypy3"
#      install:
#      # cryptography > 3.3 is not currently built for pypy, and we don't want to install rust to build it
#      - pip install --extra-index-url https://antocuni.github.io/pypy-wheels/manylinux2010 cryptography==3.3.1
#      - pip install .
#      - pip install -r requirements-dev.txt
#      - rm -rf build/
#
#
#script: ./script/test -vv
