#!/bin/bash

# This script serves as an entrypoint for our docker container
wait_elasticsearch() {
  echo "Waiting for ES to boot: "
  #max wait time
  i=50
  while ((i > 0 )); do
    echo -n "."
    sleep 1
    curl -s -o /dev/null http://localhost:9200/_cluster/health|grep green && echo "ok." && break
    i=$(( i - 1 ))
  done
}

if [ "$1" == "bash" ]; then
  /bin/bash
elif [ "$1" == "test" ]; then
  shift
  export PYTHONDONTWRITEBYTECODE=true

  # TODO move this into debian deps
  if ! sudo service elasticsearch status > /dev/null; then
    wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb;
    sudo dpkg -i elasticsearch-1.4.4.deb;
    rm elasticsearch-*.deb
  else
    echo "Elastic search already installed"
  fi
  sudo service elasticsearch start
  #wait for ES to start
  wait_elasticsearch
  #fail from now if tests fail
  set -e
  #run tests
  nosetests -e '.*integration.*'
  /virtualenv/pypy/bin/nosetests tests/utils/test_{kvstore,decorator,dict}.py
else
  echo "Invalid option. Please invoke the container with 'bash' or 'test'" >&2
  exit 1
fi
