#!/bin/bash
set -e

# API docs
sphinx-apidoc --separate --module-first --output-dir docs/api/ simpleflow
sphinx-apidoc --separate --module-first --output-dir docs/api/ swf
sed -i'' -e 's/simpleflow package/API simpleflow/' docs/api/simpleflow.rst
sed -i'' -e 's/swf package/API swf/' docs/api/swf.rst

# Site generation
cd docs/
make html
