#!/bin/bash
set -e

docker run -it \
  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
  -e LOG_LEVEL=$LOG_LEVEL \
  -e PYTHONDONTWRITEBYTECODE=true \
  -e SWF_DOMAIN=$SWF_DOMAIN \
  -v $(pwd):/code/simpleflow \
  simpleflow bash
