#!/bin/bash
set -e

ENV=$1
shift || true

if [[ $ENV != python2.7 && $ENV != pypy && $ENV != python3.5 ]]; then
  echo "Usage: $0 <python2.7|pypy|python3.5> [args passed to ./script/test]" >&2
  exit 1
fi

set -x
docker run -it -v $(pwd):/tmp/simpleflow quay.io/travisci/travis-python \
  sudo -u travis /bin/bash -c "
    export HOME=/home/travis && \
    cd /tmp/simpleflow && \
    source ~/virtualenv/$ENV/bin/activate && \
    pip install . && \
    pip install -r requirements-dev.txt && \
    ./script/test $*"
