name: "Build simpleflow"

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v3
        with:
          name: simpleflow
          path: dist
