# Adapted from: https://github.com/sesh/thttp/blob/main/.github/workflows/ci.yml
# Thanks!

name: Python Checks

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            python-version: "3.10"
          - os: "ubuntu-latest"
            python-version: "3.11"
          - os: "ubuntu-latest"
            python-version: "3.12"
          - os: "ubuntu-latest"
            python-version: "3.13"
          - os: "ubuntu-latest"
            python-version: "3.14"
          - os: "ubuntu-latest"
            python-version: "pypy-3.11"

    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up UV
        id: setup-uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run --frozen --all-extras --group=dev pytest

  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up UV
        id: setup-uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Run prek
        run: uvx prek run --all-files

  publish:
    name: Publish package to PyPI
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - tests
      - lint
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up UV
        id: setup-uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Build wheel & sdist
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
