QUERY_URLS_FIELDS = (
    "url",
    "protocol",
    "path",
    "query",
    "query_string_keys",
    "query_string_keys_order",
    "query_string_items",
    "date_crawled",
    "depth",
    "http_code",
    "delay1",
    "delay2",
    "bytesize",
    "inlinks_nb",
    "inlinks_follow_nb",
    "inlinks_link_nofollow_nb",
    "inlinks_meta_nofollow_nb",
    "inlinks_robots_nofollow_nb",
    "outlinks_follow_nb",
    "outlinks_link_nofollow_nb",
    "outlinks_meta_nofollow_nb",
    "outlinks_robots_nofollow_nb",
    "outlinks_config_nofollow_nb",
    "metadata.title",
    "metadata.description",
    "metadata.h1",
    "metadata.h2",
    "metadata_nb.title",
    "metadata_nb.description",
    "metadata_nb.h1",
    "metadata_nb.h2",
    "metadata_duplicate.h1",
    "metadata_duplicate.title",
    "metadata_duplicate.description",
    "metadata_duplicate_nb.h1",
    "metadata_duplicate_nb.title",
    "metadata_duplicate_nb.description",
    "inlinks_follow_urls",
    "inlinks_link_nofollow_urls",
    "inlinks_meta_nofollow_urls",
    "inlinks_robots_nofollow_urls",
    "outlinks_follow_urls",
    "outlinks_link_nofollow_urls",
    "outlinks_meta_nofollow_urls",
    "outlinks_robots_nofollow_urls",
    "outlinks_config_nofollow_urls",
    "redirect_from",
    "redirect_to",
    "canonical_url",
    "redirects_nb"
)

QUERY_TAGGING_FIELDS = (
    'resource_type',
)

QUERY_URLS_IDS = (
    "metadata_duplicate.h1",
    "metadata_duplicate.title",
    "metadata_duplicate.description",
    "redirect_to.url",
    "inlinks_follow_urls",
    "inlinks_link_nofollow_urls",
    "inlinks_meta_nofollow_urls",
    "inlinks_robots_nofollow_urls",
    "outlinks_follow_urls",
    "outlinks_link_nofollow_urls",
    "outlinks_meta_nofollow_urls",
    "outlinks_robots_nofollow_urls",
    "outlinks_config_nofollow_urls",
)

QUERY_URLS_DEFAULT_VALUES = {
    "inlinks_nb": 0,
    "inlinks_follow_nb": 0,
    "inlinks_link_nofollow_nb": 0,
    "inlinks_meta_nofollow_nb": 0,
    "inlinks_robots_nofollow_nb": 0,
    "outlinks_follow_nb": 0,
    "outlinks_link_nofollow_nb": 0,
    "outlinks_meta_nofollow_nb": 0,
    "outlinks_robots_nofollow_nb": 0,
    "outlinks_config_nofollow_nb": 0
}
