QUERY_URLS_FIELDS = (
    "url",
    "protocol",
    "path",
    "query",
    "query_string_keys",
    "query_string_keys_order",
    "query_string_items",
    "date",
    "depth",
    "http_code",
    "delay1",
    "delay2",
    "outlinks_internal_follow_nb",
    "outlinks_internal_nofollow_nb",
    "outlinks_external_follow_nb",
    "outlinks_external_nofollow_nb",
    "bytesize",
    "inlinks_nb",
    "inlinks_follow_nb",
    "metadata.title",
    "metadata.description",
    "metadata.h1",
    "metadata.h2",
    "metadata_nb.title",
    "metadata_nb.description",
    "metadata_nb.h1",
    "metadata_nb.h2",
    "outlinks_follow_ids",
    "outlinks_nofollow_ids",
    "inlinks_follow_ids",
    "inlinks_nofollow_ids"
)

QUERY_TAGGING_FIELDS = (
    'resource_type',
)
