SUGGEST_CLUSTERS = [
    ('pattern', 'path'),
    ('pattern', 'qskey'),
    ('metadata', 'title'),
    ('metadata', 'h1'),
    ('metadata', 'h2'),
]

CLUSTER_TYPES_ACRONYMS = {
    'P': 'pattern',
    'M': 'metadata'
}

QUERY_FIELDS = (
    "url",
    "protocol",
    "path",
    "query",
    "query_string_keys",
    "query_string_keys_order",
    "query_string_items",
    "date_crawled",
    "depth",
    "http_code",
    "delay1",
    "delay2",
    "bytesize",
    "suggest",

    "inlinks_internal_nb",
    "inlinks_internal_nb.total",
    "inlinks_internal_nb.follow",
    "inlinks_internal_nb.follow_unique",
    "inlinks_internal_nb.nofollow",
    "inlinks_internal_nb.nofollow_combinations",

    "outlinks_internal_nb",
    "outlinks_internal_nb.total",
    "outlinks_internal_nb.follow_unique",
    "outlinks_internal_nb.follow",
    "outlinks_internal_nb.nofollow_combinations",
    "outlinks_internal_nb.nofollow",

    "outlinks_external_nb",
    "outlinks_external_nb.total",
    "outlinks_external_nb.follow",
    "outlinks_external_nb.nofollow",
    "outlinks_external_nb.nofollow_combinations",

    "inlinks_internal",
    "outlinks_internal",
    "metadata",
    "metadata.title",
    "metadata.description",
    "metadata.h1",
    "metadata.h2",
    "metadata_nb",
    "metadata_nb.title",
    "metadata_nb.description",
    "metadata_nb.h1",
    "metadata_nb.h2",
    "metadata_duplicate",
    "metadata_duplicate.h1",
    "metadata_duplicate.title",
    "metadata_duplicate.description",
    "metadata_duplicate_nb.h1",
    "metadata_duplicate_nb.title",
    "metadata_duplicate_nb.description",
    "redirects_from_nb",
    "redirects_from",
    "redirects_to",
    "canonical_url",
)
